@hostAuth = http://localhost:3000/auth
@hostTask = http://localhost:3000/tasks
@user_name = agussutarom
@user_password = Enteraj4!
### AUTH
POST {{hostAuth}}/sign-up
Accept: application/json
Content-Type: application/json

{
  "username": "{{user_name}}",
  "password": "{{user_password}}"
}

###
# @name postSignIn
POST {{hostAuth}}/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "{{user_name}}",
  "password": "{{user_password}}"
}


###
@token = {{ postSignIn.response.body.accessToken }}

###
GET {{hostTask}}
Accept: application/json
Authorization: BEARER {{token}}

### empty post body on create
POST {{hostTask}}
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "title": "guitar hero",
  "description": "playing"
}

###
POST {{hostTask}}
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "title": "Pekerjaan Rumah",
  "description": "Mengerjakan berbagai pekerjaan rumah"
}

###
POST {{hostTask}}
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "title": "Pekerjaan Sekolah",
  "description": "Mengerjakan berbagai pekerjaan sekolah"
}

###
# @name postTask
POST {{hostTask}}
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "title": "Pekerjaan Kantor Baru",
  "description": "Mengerjakan berbagai hidup pekerjaan Kantor"
}

###
@lastId = {{ postTask.response.body.id }}

###
GET {{hostTask}}/{{lastId}}
Accept: application/json
Authorization: BEARER {{token}}

###
PUT {{hostTask}}/{{lastId}}
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "title": "Update Baru",
  "description": "Mengerjakan berbagai hidup pekerjaan update"
}

###
PATCH {{hostTask}}/{{lastId}}/status
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "status": "DONE"
}

###
DELETE {{hostTask}}/{{lastId}}
Accept: application/json
Authorization: BEARER {{token}}

### cross hack to other user task, view by id mode
GET {{hostTask}}/2e656ba0-0157-405a-aa4d-4c0c788ebe48
Accept: application/json
Authorization: BEARER {{token}}

### cross hack to other user task, patch mode
PATCH {{hostTask}}/2e656ba0-0157-405a-aa4d-4c0c788ebe48/status
Accept: application/json
Content-Type: application/json
Authorization: BEARER {{token}}

{
  "status": "DONE"
}

### cross hack to other user task, delete mode
DELETE {{hostTask}}/2e656ba0-0157-405a-aa4d-4c0c788ebe48
Accept: application/json
Authorization: BEARER {{token}}

### with filter
GET {{hostTask}}?status=OPEN&search=a
Accept: application/json
Authorization: BEARER {{token}}
