### AUTH
POST http://localhost:3000/auth/sign-up
Accept: application/json
Content-Type: application/json

{
  "username": "taroom3",
  "password": "Enteraj4!"
}

###
POST http://localhost:3000/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "taroom3",
  "password": "Enteraj4!"
}


###
GET http://localhost:3000/tasks
Accept: application/json

### empty post body on create
POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "a",
  "description": ""
}

###
POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Rumah",
  "description": "Mengerjakan berbagai pekerjaan rumah"
}

###
POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Sekolah",
  "description": "Mengerjakan berbagai pekerjaan sekolah"
}

###
POST http://localhost:3000/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Kantor",
  "description": "Mengerjakan berbagai hidup pekerjaan Kantor"
}

###
GET http://localhost:3000/tasks/a1892a3b-4878-477a-a75b-fddc0c3f69f5
Accept: application/json


###
PUT http://localhost:3000/tasks/bfe5571e-301d-4ebe-93a4-d8007d75d6b5
Accept: application/json
Content-Type: application/json

{
  "title": "Update",
  "description": "Mengerjakan berbagai hidup pekerjaan update"
}

###
PATCH http://localhost:3000/tasks/bfe5571e-301d-4ebe-93a4-d8007d75d6b5/status
Accept: application/json
Content-Type: application/json

{
  "status": "DONE"
}

###
DELETE http://localhost:3000/tasks/dcc9ebbb-53da-440c-a137-b70b1ad43950
Accept: application/json


### with filter
GET http://localhost:3000/tasks?status=DONE&search=sekolah
Accept: application/json
