@hostAuth = http://localhost:3000/auth
@hostTask = http://localhost:3000/task
@user_name = agustaroom
@user_password = Enteraj4!
### AUTH
POST {{hostAuth}}/sign-up
Accept: application/json
Content-Type: application/json

{
  "username": "{{user_name}}",
  "password": "{{user_password}}"
}

###
# @name postSignIn
POST {{hostAuth}}/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "{{user_name}}",
  "password": "{{user_password}}"
}


###
@token = {{ postSignIn.response.body.accessToken }}

###
GET {{hostTask}}
Accept: application/json

### empty post body on create
POST {{hostTask}}
Accept: application/json
Content-Type: application/json

{
  "title": "a",
  "description": ""
}

###
POST {{hostTask}}
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Rumah",
  "description": "Mengerjakan berbagai pekerjaan rumah"
}

###
POST {{hostTask}}
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Sekolah",
  "description": "Mengerjakan berbagai pekerjaan sekolah"
}

###
POST {{hostTask}}
Accept: application/json
Content-Type: application/json

{
  "title": "Pekerjaan Kantor",
  "description": "Mengerjakan berbagai hidup pekerjaan Kantor"
}

###
GET {{hostTask}}/a1892a3b-4878-477a-a75b-fddc0c3f69f5
Accept: application/json


###
PUT {{hostTask}}/bfe5571e-301d-4ebe-93a4-d8007d75d6b5
Accept: application/json
Content-Type: application/json

{
  "title": "Update",
  "description": "Mengerjakan berbagai hidup pekerjaan update"
}

###
PATCH {{hostTask}}/bfe5571e-301d-4ebe-93a4-d8007d75d6b5/status
Accept: application/json
Content-Type: application/json

{
  "status": "DONE"
}

###
DELETE {{hostTask}}/dcc9ebbb-53da-440c-a137-b70b1ad43950
Accept: application/json


### with filter
GET {{hostTask}}?status=DONE&search=sekolah
Accept: application/json
